version: "3.0"

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    container_name: assignment_store_mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    container_name: assignment_store_web
    stdin_open: true
    tty: true
    depends_on:
      - mysql

volumes:
  mysql:
  node_modules:
