default: &default
  adapter: mysql2
  encoding: <%= ENV.fetch("MYSQL_ENDCODING", "utf8mb4")%>
  collation: <%= ENV.fetch("MYSQL_COLLATION", "utf8mb4_general_ci")%>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "") %>
  host: <%= ENV.fetch("MYSQL_HOST", "") %>
  socket: <%= ENV.fetch("MYSQL_SOCK", "") %>

development:
  <<: *default
  database: assignment_store_development

test:
  <<: *default
  database: assignment_store_test

production:
  <<: *default
  database: assignment_store_production
  username: assignment_store
  password: <%= ENV['ASSIGNMENT_STORE_DATABASE_PASSWORD'] %>
